### ISSUE TITLE
未来更新线路图

### ISSUE THREAD

**Issue by ycrao** [yascmf/base#1]
这是官方规划的未来更新内容，你可以在下面回复你所期待的功能。
### 前台
- [x] 宣传页面
- [ ] QQ第三方登录
- [ ] GitHub第三方登录
- [ ] 会员系统 
- [ ] 使用 `Markdown`  编辑器发文
### 管理后台
- [x] 文章
- [x] 分类
- [x] `Markdown` 编辑器支持（规划使用  `editor.md` ）
- [ ] 会员管理
- [x] 缓存
- [x] 管理员用户
- [x] 角色
- [x] 权限
- [x] 系统配置
- [x] 系统日志
### API服务

>   目录官方 `API` 站点并无任何限制，均为公开性的 `API` ，开发者可以根据自身需要自行做出限制。
- [x] IP归属地服务（由第三方在线 [淘宝IP](http://ip.taobao.com/) 提供）
- [x] 身份证证号归属查询服务（由内建的第三方composer包 `douyasi/identity-card` 提供） 
- [x] 汉字转拼音（由内建的第三方composer包 `overtrue/laravel-pinyin` 提供 ）
### 其它
- [x] 静态资源类库剥离及CDN部署
- [x] 扩展分页样式
- [x] 自定义校验规则
- [x] 多站点部署与路由限制
- [x] 官方文档支持（内容正在更新中）
- [x] base衍生支持版本开发（开发中）
- [x] 数据库 `migration` 支持

**Comment by szwss** [comment]
全部都期待 ，谢谢哈，不错的系统

**Comment by anjido** [comment]
会员系统, 编辑器
