### ISSUE TITLE
图片上传

### ISSUE THREAD

**Issue by eleven0220** [yascmf/base#3]
图片上传可以一次上传多张图片的吗？

**Comment by ycrao** [comment]
@eleven0220 不知道你所说的上传是哪个地方的。

缩略图目前回传的是图片路径，没有多图的必要。
![image](https://cloud.githubusercontent.com/assets/3280204/18244202/613f80f6-7391-11e6-9628-92c75bb45488.png)
默认 `CKEditor`  编辑器是可以上传图片的，但一次多图也是无法办到的。如何你有需求，可以移除 `CKEditor` 编辑器，使用 `wangEditor` 编辑器。

从下面链接可以获取本人所写的 `wangEditor` 适配包：
https://phphub.org/topics/2737
https://github.com/douyasi/laravel-wang-editor

未来 `YASCMF` 版本，后台将使用 `editor.md` 编辑器，以提供更好的 `Markdown` 写作支持。
