### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by daimajinku** [yascmf/base#6]
composer install  

  - Installing douyasi/identity-card (1.2): Downloading (failed)    Failed to do
wnload douyasi/identity-card from dist: The "https://packagist.phpcomposer.com/f
iles/douyasi/identity-card/da5ae04975d3d95c7eda3e0b9ee623f70cec5872.zip" file co
uld not be downloaded (HTTP/1.1 404 Not Found)

**Comment by ycrao** [comment]
网络问题吧，或者尝试将依赖版本提高到 `"douyasi/identity-card": "~2.0"`
